[package]
name = "vdl"
version = "0.1.0"
edition = "2024"

[dependencies]
basic-toml = "0.1.9"
dirs = "6.0.0"
eyre = "0.6.12"
lazy_static = "1.5.0"
serde = { version = "1.0.218", features = ["derive"] }
tinyjson = "2.5.1"
